require( "deflibs.defold" )
local Map = require( "nexus.map" )

local Game = require( "nexus.game" )
local lua = require( "deflibs.lualib" )
local Host = require( "nexus.host" )

-- global ---------------------------
GAME = Game.new( "MultiPlayerGame" )
-------------------------------------


function init( self )
	lua.randomize()
	msg.post( "main:/screenmaster", "load", { level = "setup" } ) 
end

